### PR TITLE
Link to /usr/local/bin if OSX El Capitan (or later)

### PR DESCRIPTION
**Pull request by cielavenir**
https://github.com/manastech/omnibus-crystal/issues/6

### CODE REVIEW

**Comment by cielavenir** [comment]
Well, since I'm a MacPorts user rather than Homebrew user, I need to use pkg. So I have to get it working until 1.0.0 release. I tried to fix by my own. It looks working but it might be a mess because I'm not good at bash. Review is welcomed.

**Comment by cielavenir** [comment]
Well, well... Now I can assure I will not be upset even if you (somehow) close this pull request...
http://qiita.com/cielavenir/items/c11a1e6a81c8316d05a6

**Comment by mohd-akram** [comment]
Can this be merged? It looks fine (although I don't think you should bother checking the OS version). Will also need a `install -d $INSTALL_PATH/bin` because `/usr/local/bin` is not there by default. The installer is effectively broken on macOS.

**Review by mverzilli — APPROVED** [review]

**Comment by mverzilli** [comment]
@matiasgarciaisaia this seems ok, consider it for the next release. Actually... how is it working now? Are we even using this code to build for OS X lately?

**Comment by matiasgarciaisaia** [comment]
It seems it is simply not working. Seems that almost everyone uses Homebrew (which doesn't rely on this script), so that's why we haven't noticed.

I'm testing this and probably merging in a few hours 👍

**Comment by matiasgarciaisaia** [comment]
Awesome catch, @cielavenir!

Thanks for the fix :)

**Pull request merged**
